### ISSUE TITLE
TrackRecordingService: service connection leaks

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1052]
I was able to reproduce again. Starting the track recording, push the power button, so the screen of you phone turns black and OT runs in the background. Wait until the first notification. Then unlock the phone again and stop the recording. Go back to the track list and you see that there is still a track recording running.

This is the logcat:

```

2021-12-17 14:48:34.411 29612-29612/de.dennisguse.opentracks.debug E/ActivityThread: Service de.dennisguse.opentracks.services.TrackRecordingService has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@284d451 that was originally bound here
    android.app.ServiceConnectionLeaked: Service de.dennisguse.opentracks.services.TrackRecordingService has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@284d451 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1941)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1813)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1792)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1899)
        at android.app.ContextImpl.bindService(ContextImpl.java:1829)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:774)
        at android.speech.tts.TextToSpeech.connectToEngine(TextToSpeech.java:849)
        at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:819)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:772)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:751)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:735)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncement.start(VoiceAnnouncement.java:122)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncementManager.restore(VoiceAnnouncementManager.java:62)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncementManager.setFrequency(VoiceAnnouncementManager.java:105)
        at de.dennisguse.opentracks.services.TrackRecordingService$2.onSharedPreferenceChanged(TrackRecordingService.java:110)
        at de.dennisguse.opentracks.settings.PreferencesUtils.registerOnSharedPreferenceChangeListener(PreferencesUtils.java:81)
        at de.dennisguse.opentracks.services.TrackRecordingService.onCreate(TrackRecordingService.java:148)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4650)
        at android.app.ActivityThread.access$1700(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-12-17 14:48:34.429 29612-29612/de.dennisguse.opentracks.debug E/ActivityThread: Service de.dennisguse.opentracks.services.TrackRecordingService has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@c88b6db that was originally bound here
    android.app.ServiceConnectionLeaked: Service de.dennisguse.opentracks.services.TrackRecordingService has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@c88b6db that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1941)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1813)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1792)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1899)
        at android.app.ContextImpl.bindService(ContextImpl.java:1829)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:774)
        at android.speech.tts.TextToSpeech.connectToEngine(TextToSpeech.java:849)
        at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:819)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:772)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:751)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:735)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncement.start(VoiceAnnouncement.java:122)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncementManager.restore(VoiceAnnouncementManager.java:62)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncementManager.setFrequency(VoiceAnnouncementManager.java:100)
        at de.dennisguse.opentracks.services.TrackRecordingService$2.onSharedPreferenceChanged(TrackRecordingService.java:107)
        at de.dennisguse.opentracks.settings.PreferencesUtils.registerOnSharedPreferenceChangeListener(PreferencesUtils.java:81)
        at de.dennisguse.opentracks.services.TrackRecordingService.onCreate(TrackRecordingService.java:148)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4650)
        at android.app.ActivityThread.access$1700(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-12-17 14:48:58.117 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: stopped(false) old=true
2021-12-17 14:48:58.145 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Binding the service.
2021-12-17 14:48:58.167 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: stopped(false) old=false
2021-12-17 14:48:58.167 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Starting the service.
2021-12-17 14:48:58.168 29612-9847/de.dennisguse.opentracks.debug I/TrackDataHub: Not reloading track 46
2021-12-17 14:48:58.169 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Binding the service.
2021-12-17 14:48:58.169 29612-29612/de.dennisguse.opentracks.debug W/TrackRecordingActivity: could not get TrackRecordingService
2021-12-17 14:48:58.170 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Binding the service.
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err: java.lang.NoSuchFieldException: stats_custom_layout_fields_default_value_19
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at java.lang.Class.getField(Class.java:1604)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.getMultiTypedArray(PreferencesUtils.java:564)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.buildDefaultFields(PreferencesUtils.java:578)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.buildDefaultLayout(PreferencesUtils.java:584)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.getCustomLayout(PreferencesUtils.java:595)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.fragments.StatisticsRecordingFragment.lambda$new$0$de-dennisguse-opentracks-fragments-StatisticsRecordingFragment(StatisticsRecordingFragment.java:70)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.fragments.StatisticsRecordingFragment$$ExternalSyntheticLambda0.onSharedPreferenceChanged(Unknown Source:2)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.registerOnSharedPreferenceChangeListener(PreferencesUtils.java:81)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.fragments.StatisticsRecordingFragment.onResume(StatisticsRecordingFragment.java:128)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.Activity.performResume(Activity.java:8378)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4897)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4944)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.os.Looper.loop(Looper.java:246)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8633)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug E/PreferencesUtils: stats_custom_layout_fields_default_value_19
2021-12-17 14:48:58.182 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Binding the service.
2021-12-17 14:48:58.207 29612-29612/de.dennisguse.opentracks.debug I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x4f8f642 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-12-17 14:48:58.208 29612-29612/de.dennisguse.opentracks.debug I/SurfaceControl: nativeRelease nativeObject s[517925215088]
2021-12-17 14:48:58.208 29612-29612/de.dennisguse.opentracks.debug I/SurfaceControl: nativeRelease nativeObject e[517925215088]
2021-12-17 14:48:58.209 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=15 res=0x7 s={true 522757871376} ch=true fn=-1
2021-12-17 14:48:58.213 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:10957 android.view.ViewRootImpl.performTraversals:3845 android.view.ViewRootImpl.doTraversal:2618 
2021-12-17 14:48:58.213 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: [DP] pd() Asnyc report
2021-12-17 14:48:58.224 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$performDraw$1$ViewRootImpl:4668 android.view.-$$Lambda$ViewRootImpl$DJd0VUYJgsebcnSohO6h8zc_ONI.run:6 android.os.Handler.handleCallback:938 
2021-12-17 14:48:58.224 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: [DP] rdf()
2021-12-17 14:48:58.233 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingService: new status null -> RecordingStatus{trackId=null, paused=false}
2021-12-17 14:48:58.234 29612-29612/de.dennisguse.opentracks.debug D/VoiceAnnouncement: Start
```

Hope you can make any sense out of it.

_Originally posted by @pstorch in https://github.com/OpenTracksApp/OpenTracks/issues/1047#issuecomment-996739924_

**Comment by dennisguse** [comment]
Should be fixed by reworking lifecycle of TrackRecordingService.

**Comment by dennisguse** [comment]
How to recreate the issue reliably:
1. Start a recording
2. Close activity (not only move it to the background, but really swipe it away)
3. Open via notification: opens TrackRecordingActivity
4. Go to interval tab: crash

The problem is that the 2nd time TrackRecordingActivity is opened, it lost the trackId.
And since it doesn't have it anymore all operations were the trackId needs to be passed will crash (e.g.., interval tab, map, share)

We try to persist the trackId in a savedInstance, but that is not restored as it is a different (aka new) TrackRecordingActivity.

Mindblown.
@pstorch @rgmf FYI

**Comment by dennisguse** [comment]
I guess this was fixed; haven't seen it anymore.
