### ISSUE TITLE
v3.23.0 (or earlier): share track functionality is broken

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1073]
Using LineageOS and K-Mail.

```
2021-12-31 20:36:15.440 22360-22379/de.dennisguse.opentracks E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading de.dennisguse.opentracks.content.provider.ShareContentProvider uri content://de.dennisguse.opentracks.content/tracks/share_picture_png/56/2021-12-31%2014_12.png from pid=19323, uid=1000 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
2021-12-31 20:36:15.616 22360-22379/de.dennisguse.opentracks E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading de.dennisguse.opentracks.content.provider.ShareContentProvider uri content://de.dennisguse.opentracks.content/tracks/share_picture_png/56/2021-12-31%2014_12.png from pid=19323, uid=1000 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
```

**Comment by dennisguse** [comment]
Don't know what happened back then; it is just working now.
