### ISSUE TITLE
Crash while taking a photo for a marker (Google Play Crash reporting)

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1126]
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4515)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4547)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2084)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7887)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:981)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5115)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4502)
Caused by: java.lang.NullPointerException: 
  at de.dennisguse.opentracks.ui.markers.MarkerEditViewModel.onNewCameraPhoto (MarkerEditViewModel.java:115)
  at de.dennisguse.opentracks.ui.markers.MarkerEditActivity.lambda$onCreate$4$de-dennisguse-opentracks-ui-markers-MarkerEditActivity (MarkerEditActivity.java:134)
  at de.dennisguse.opentracks.ui.markers.MarkerEditActivity$$ExternalSyntheticLambda3.onActivityResult (Unknown Source:4)
  at androidx.activity.result.ActivityResultRegistry.doDispatch (ActivityResultRegistry.java:392)
  at androidx.activity.result.ActivityResultRegistry.dispatchResult (ActivityResultRegistry.java:351)
  at androidx.activity.ComponentActivity.onActivityResult (ComponentActivity.java:647)
  at androidx.fragment.app.FragmentActivity.onActivityResult (FragmentActivity.java:164)
  at android.app.Activity.dispatchActivityResult (Activity.java:8329)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5108)
```

**Comment by dennisguse** [comment]
And another one:
```
2022-02-13 19:50:05.663 20614-20614/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.dennisguse.opentracks.nightly, PID: 20614
    java.lang.NullPointerException: Attempt to invoke virtual method 'long de.dennisguse.opentracks.data.models.Track$Id.getId()' on a null object reference
        at de.dennisguse.opentracks.util.FileUtils.getPhotoDir(FileUtils.java:61)
        at de.dennisguse.opentracks.ui.markers.MarkerUtils.createTakePictureIntent(MarkerUtils.java:48)
        at de.dennisguse.opentracks.ui.markers.MarkerEditActivity.createMarkerWithPicture(MarkerEditActivity.java:227)
        at de.dennisguse.opentracks.ui.markers.MarkerEditActivity.onOptionsItemSelected(MarkerEditActivity.java:181)
```

**Comment by dennisguse** [comment]
Did happen anymore; might be gone ;)
