### ISSUE TITLE
Auto-Export + Export All Fail while Export via Share remains only working export option

### ISSUE THREAD

**Issue by Der-Flip** [OpenTracksApp/OpenTracks#1141]
**Describe the bug**
Autoexport and "export All" fail.

Autoexport: Export fails with message: check Export folder. Folder is set and correct and hasn't changed from folder set in 3.24.1
Export all: Export fails, no error message, app returns to settings menu 

**To Reproduce**
1. set export folder
2. enable auto export
3. start tracking & wait for GPS fix
4. Stop tracking

**Logcat:**
```
2022-02-26 21:35:31.893 30645-30645/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.dennisguse.opentracks, PID: 30645
    java.lang.RuntimeException: Unknown resultCode.
        at de.dennisguse.opentracks.io.file.exporter.ExportServiceResultReceiver.onReceiveResult(ExportServiceResultReceiver.java:38)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

**To Reproduce**
1. set export folder (sd card OR internal, doesn't matter)
2. have multiple tracks
3. export all

**Logcat:**
```
2022-02-26 21:32:02.603 26615-26615/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.dennisguse.opentracks, PID: 26615
    java.lang.RuntimeException: Unknown resultCode.
        at de.dennisguse.opentracks.io.file.exporter.ExportServiceResultReceiver.onReceiveResult(ExportServiceResultReceiver.java:38)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

**Technical information**
 - Device: Xiaomi Redmi 9C
 - OS: Android 10 QP1A-190711.020
 - MIUI 12.0.11 Stable
 - OpenTracks version: v3.25.0

**Additional Info:**
I did a downgrade to 3.24.1:
  Autoexport set to the same folder again works flawlessly
  Export All works flawlessly
After updating the App tp 3.25.0 again (post downgrade):
  Autoexport fails
  Export All fails.

Multiexport by selecting multiple Tracks and Exporting via the Share button (in my case then cx explorer) remains the only option to export the tracks to device

I'm happy to answer any more question, but I'll be running 3.24.1 for the time being.
If you'd like to have a look at the logcats let me know and I'll e-mail them to you.

**Comment by pstorch** [comment]
This will be fixed by https://github.com/OpenTracksApp/OpenTracks/pull/1136

**Comment by Der-Flip** [comment]
Oh okay.
I read that ticket, and was about to reply to it rather than open a new one, but as it was very reliably failing to export (compared to #1080 failing just occasionally), the "export all" was failing too, both of which worked perfectly fine in 3.24.1 and 3.24.0 and with the log reading quite a bit different I decided to open a new one.
My apologies and thanks for the effort!

**Comment by pstorch** [comment]
@Der-Flip no worries, there are two different issues. But my PR contains a fix for the issue you discovered, because I stumbled upon it while investigating the older issue.

**Comment by pstorch** [comment]
@Der-Flip a fix is in our nightly build. Would be great if you can test it, if it fully fixes this issue.

**Comment by dennisguse** [comment]
@Der-Flip Please re-open if the issues is not fixed for you.
Fix was released in [v3.25.1](https://github.com/OpenTracksApp/OpenTracks/releases/tag/v3.25.1)

**Comment by Der-Flip** [comment]
hi, I apologize for the delay... didn't notice there had been an update and github didn'*t send notifications either, weirdly enough.
Export does indeed work as intended.

**Comment by dennisguse** [comment]
@Der-Flip :metal:
