### ISSUE TITLE
Security Exception when trying to store Blutooth sensor data

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#1165]
```
03-31 16:39:07.591 20611 27265 D BluetoothConnectionManager: Received data from E5:F7:CA:AB:CD:EF
03-31 16:39:07.591 20611 28467 D BluetoothConnectionManager: Received data from E5:F7:CA:AB:CD:EF
03-31 16:39:07.591 20611 26888 D BluetoothConnectionManager: Received data from E5:F7:CA:AB:CD:EF
03-31 16:39:07.592 20611 26886 D BluetoothConnectionManager: Received data from E5:F7:CA:AB:CD:EF
03-31 16:39:07.593 20611 28467 I opentracks: cadence read: 124.0
03-31 16:39:07.593 20611 26888 D BluetoothConnectionManager: Decoded data from E5:F7:CA:AB:CD:EF: sensorAddress='E5:F7:CA:AB:CD:EF heart=HeartRate{value=92.0 bpm}
03-31 16:39:07.593 20611 28467 D BluetoothConnectionManager: Decoded data from E5:F7:CA:AB:CD:EF: sensorAddress='E5:F7:CA:AB:CD:EF
03-31 16:39:07.593 20611 28467 D BluetoothRemoteSensorManager: Previous: sensorAddress='E5:F7:CA:AB:CD:EF; CurrentsensorAddress='E5:F7:CA:AB:CD:EF
03-31 16:39:07.593 20611 26888 D TrackRecordingManager: Not recording TrackPoint
03-31 16:39:07.594 20611 27265 D BluetoothConnectionManager: Decoded data from E5:F7:CA:AB:CD:EF: sensorAddress='E5:F7:CA:AB:CD:EF heart=HeartRate{value=92.0 bpm}
03-31 16:39:07.595 20611 26886 I opentracks: cadence read: 124.0
03-31 16:39:07.595 20611 26886 D BluetoothConnectionManager: Decoded data from E5:F7:CA:AB:CD:EF: sensorAddress='E5:F7:CA:AB:CD:EF
03-31 16:39:07.599 20611 26886 D BluetoothRemoteSensorManager: Previous: sensorAddress='E5:F7:CA:AB:CD:EF; CurrentsensorAddress='E5:F7:CA:AB:CD:EF
03-31 16:39:07.599 20611 28467 D TrackRecordingManager: Not recording TrackPoint
03-31 16:39:07.626   789  2876 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
03-31 16:39:07.626   789  2876 D vendor.qti.bluetooth@1.0-ibs_handler: SerialClockVote: vote for UART CLK OFF
03-31 16:39:07.652 20611 20611 D AndroidRuntime: Shutting down VM
03-31 16:39:07.653 20611 26886 W BluetoothGatt: Unhandled exception in callback
03-31 16:39:07.653 20611 26886 W BluetoothGatt: java.lang.SecurityException: Permission Denial: writing de.dennisguse.opentracks.data.ShareContentProvider uri content://de.dennisguse.opentracks.debug.content/trackpoints from pid=0, uid=1002 requires the provider be exported, or grantUriPermission()
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.content.ContentProvider.enforceWritePermissionInner(ContentProvider.java:896)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.content.ContentProvider$Transport.enforceWritePermission(ContentProvider.java:696)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:322)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.content.ContentResolver.insert(ContentResolver.java:2149)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.content.ContentResolver.insert(ContentResolver.java:2111)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at de.dennisguse.opentracks.data.ContentProviderUtils.insertTrackPoint(ContentProviderUtils.java:713)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at de.dennisguse.opentracks.services.TrackRecordingManager.insertTrackPointHelper(TrackRecordingManager.java:242)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at de.dennisguse.opentracks.services.TrackRecordingManager.insertTrackPoint(TrackRecordingManager.java:237)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at de.dennisguse.opentracks.services.TrackRecordingManager.onNewTrackPoint(TrackRecordingManager.java:204)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at de.dennisguse.opentracks.services.TrackRecordingService.newTrackPoint(TrackRecordingService.java:298)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.onNewTrackPoint(TrackPointCreator.java:128)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.onChange(TrackPointCreator.java:122)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at de.dennisguse.opentracks.sensors.BluetoothRemoteSensorManager.onChanged(BluetoothRemoteSensorManager.java:213)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at de.dennisguse.opentracks.sensors.BluetoothConnectionManager$1.onCharacteristicChanged(BluetoothConnectionManager.java:114)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt$1$8.run(BluetoothGatt.java:478)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:780)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:41)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:472)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:306)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.os.Binder.execTransactInternal(Binder.java:1159)
03-31 16:39:07.653 20611 26886 W BluetoothGatt: 	at android.os.Binder.execTransact(Binder.java:1123)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: FATAL EXCEPTION: main
03-31 16:39:07.654 20611 20611 E AndroidRuntime: Process: de.dennisguse.opentracks.debug, PID: 20611
03-31 16:39:07.654 20611 20611 E AndroidRuntime: java.lang.RuntimeException: LastTrackPoint: TrackPoint{id=null, time=2022-03-31T20:39:07.593Z, latitude=null, longitude=null, horizontalAccuracy=null, altitude=null, speed=Speed{speed_mps=1.59375}, bearing=null, sensorDistance=Distance{distance_m=7.699999999999989}, type=SENSORPOINT(2), heartRate_bpm=HeartRate{value=92.0 bpm}, cadence_rpm=Cadence{value=124.0 rpm}, power=null, altitudeGain_m=null, altitudeLoss_m=null}
03-31 16:39:07.654 20611 20611 E AndroidRuntime: TrackPoint: TrackPoint{id=null, time=2022-03-31T20:39:07.591Z, latitude=[redacted], longitude=[redacted], horizontalAccuracy=Distance{distance_m=9.648000717163086}, altitude=Altitude{altitude_m=67.6724853515625WGS84}, speed=Speed{speed_mps=1.58984375}, bearing=null, sensorDistance=Distance{distance_m=2.3000000000000114}, type=TRACKPOINT(0), heartRate_bpm=HeartRate{value=92.0 bpm}, cadence_rpm=Cadence{value=124.0 rpm}, power=null, altitudeGain_m=null, altitudeLoss_m=null}
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.stats.TrackStatistics.addMovingTime(TrackStatistics.java:238)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.stats.TrackStatisticsUpdater.addTrackPoint(TrackStatisticsUpdater.java:177)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingManager.insertTrackPointHelper(TrackRecordingManager.java:243)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingManager.insertTrackPoint(TrackRecordingManager.java:237)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingManager.onNewTrackPoint(TrackRecordingManager.java:204)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingService.newTrackPoint(TrackRecordingService.java:298)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.onNewTrackPoint(TrackPointCreator.java:128)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.services.handlers.GPSHandler.onLocationChanged(GPSHandler.java:130)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at android.location.LocationManager$LocationListenerTransport.acceptLocation(LocationManager.java:2745)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at android.location.LocationManager$LocationListenerTransport.lambda$enkW18B0WwpQkSIMmVChmQ2YwC8(Unknown Source:0)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at android.location.-$$Lambda$LocationManager$LocationListenerTransport$enkW18B0WwpQkSIMmVChmQ2YwC8.accept(Unknown Source:6)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:292)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: Caused by: java.lang.RuntimeException: Moving time cannot be negative
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.stats.TrackStatistics.addMovingTime(TrackStatistics.java:245)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	at de.dennisguse.opentracks.stats.TrackStatistics.addMovingTime(TrackStatistics.java:236)
03-31 16:39:07.654 20611 20611 E AndroidRuntime: 	... 20 more
03-31 16:39:07.654 20611 27265 W BluetoothGatt: Unhandled exception in callback
03-31 16:39:07.654 20611 27265 W BluetoothGatt: java.lang.SecurityException: Permission Denial: writing de.dennisguse.opentracks.data.ShareContentProvider uri content://de.dennisguse.opentracks.debug.content/trackpoints from pid=0, uid=1002 requires the provider be exported, or grantUriPermission()
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.content.ContentProvider.enforceWritePermissionInner(ContentProvider.java:896)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.content.ContentProvider$Transport.enforceWritePermission(ContentProvider.java:696)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:322)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.content.ContentResolver.insert(ContentResolver.java:2149)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.content.ContentResolver.insert(ContentResolver.java:2111)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at de.dennisguse.opentracks.data.ContentProviderUtils.insertTrackPoint(ContentProviderUtils.java:713)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at de.dennisguse.opentracks.services.TrackRecordingManager.insertTrackPointHelper(TrackRecordingManager.java:242)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at de.dennisguse.opentracks.services.TrackRecordingManager.insertTrackPoint(TrackRecordingManager.java:237)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at de.dennisguse.opentracks.services.TrackRecordingManager.onNewTrackPoint(TrackRecordingManager.java:204)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at de.dennisguse.opentracks.services.TrackRecordingService.newTrackPoint(TrackRecordingService.java:298)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.onNewTrackPoint(TrackPointCreator.java:128)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.onChange(TrackPointCreator.java:122)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at de.dennisguse.opentracks.sensors.BluetoothRemoteSensorManager.onChanged(BluetoothRemoteSensorManager.java:213)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at de.dennisguse.opentracks.sensors.BluetoothConnectionManager$1.onCharacteristicChanged(BluetoothConnectionManager.java:114)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt$1$8.run(BluetoothGatt.java:478)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:780)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:41)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:472)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:306)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.os.Binder.execTransactInternal(Binder.java:1159)
03-31 16:39:07.654 20611 27265 W BluetoothGatt: 	at android.os.Binder.execTransact(Binder.java:1123)
03-31 16:39:07.661  1004  4625 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
03-31 16:39:07.662  1004  4823 W ActivityTaskManager:   Force finishing activity de.dennisguse.opentracks.debug/de.dennisguse.opentracks.TrackRecordingActivity
```

So we got our moving time debug, but notice there is a java.lang.SecurityException before that even.

_Originally posted by @brianjmurrell in https://github.com/OpenTracksApp/OpenTracks/issues/1151#issuecomment-1085161333_

**Comment by dennisguse** [comment]
I guess, we need to pass a handler to `BluetoothDevice.connectGatt()` - so the callback happens in our thread.
This might allow us to avoid synchronization in TrackPointCreator.

**Comment by dennisguse** [comment]
Sadly, this new API requires SDK level 26.
So, we have to deploy some NPE prone workaround :/
