### ISSUE TITLE
StrictMode policy violation; ~duration=18 ms: android.os.strictmode.DiskReadViolation

### ISSUE THREAD

**Issue by brianjmurrell** [OpenTracksApp/OpenTracks#1191]
I see a lot of these in my logcat:

```
04-18 17:22:30.393  2597  2597 D StrictMode: StrictMode policy violation; ~duration=18 ms: android.os.strictmode.DiskReadViolation
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1197)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:998)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.content.ContentResolver.query(ContentResolver.java:1202)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.content.ContentResolver.query(ContentResolver.java:1115)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.content.ContentResolver.query(ContentResolver.java:1071)
04-18 17:22:30.393  2597  2597 D StrictMode:    at de.dennisguse.opentracks.data.ContentProviderUtils.getTrackCursor(ContentProviderUtils.java:261)
04-18 17:22:30.393  2597  2597 D StrictMode:    at de.dennisguse.opentracks.data.ContentProviderUtils.getTrack(ContentProviderUtils.java:234)
04-18 17:22:30.393  2597  2597 D StrictMode:    at de.dennisguse.opentracks.share.ShareUtils.newShareFileIntent(ShareUtils.java:44)
04-18 17:22:30.393  2597  2597 D StrictMode:    at de.dennisguse.opentracks.TrackRecordedActivity.onOptionsItemSelected(TrackRecordedActivity.java:173)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.app.Activity.onMenuItemSelected(Activity.java:4269)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:221)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
04-18 17:22:30.393  2597  2597 D StrictMode:    at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.view.View.performClick(View.java:7448)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.view.View.performClickInternal(View.java:7425)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.view.View.access$3600(View.java:810)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.view.View$PerformClick.run(View.java:28305)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.os.Handler.handleCallback(Handler.java:938)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.os.Handler.dispatchMessage(Handler.java:99)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.os.Looper.loop(Looper.java:223)
04-18 17:22:30.393  2597  2597 D StrictMode:    at android.app.ActivityThread.main(ActivityThread.java:7664)
04-18 17:22:30.393  2597  2597 D StrictMode:    at java.lang.reflect.Method.invoke(Native Method)
04-18 17:22:30.393  2597  2597 D StrictMode:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-18 17:22:30.393  2597  2597 D StrictMode:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by dennisguse** [comment]
Those are warnings only present in the debug if builds.
The easy ones were fixed, but putting work into a non UI thread is (sadly) often not that easy - especially after the implementation is already done.
