### ISSUE TITLE
Exporting files does not work

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#127]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Export all'
3. Select folder (and press select)
4. Folder selection re-appears (or NullPointerException)

**Technical information**
 - OS: LineageOS
 - Version v3.3.1

Underlying issue seems to be:
```
01-20 03:52:41.423 E/AndroidRuntime(31594): FATAL EXCEPTION: main
01-20 03:52:41.423 E/AndroidRuntime(31594): Process: de.dennisguse.opentracks, PID: 31594
01-20 03:52:41.423 E/AndroidRuntime(31594): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.dennisguse.opentracks/de.dennisguse.opentracks.io.file.exporter.ExportActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment de.dennisguse.opentracks.fragments.FileTypeDialogFragment: could not find Fragment constructor
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.os.Looper.loop(Looper.java:193)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at java.lang.reflect.Method.invoke(Native Method)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-20 03:52:41.423 E/AndroidRunt
ime(31594): Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment de.dennisguse.opentracks.fragments.FileTypeDialogFragment: could not find Fragment constructor
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:538)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at androidx.fragment.app.FragmentManagerImpl$6.instantiate(FragmentManagerImpl.java:2851)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:85)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:2488)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:195)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:288)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at de.dennisguse.opentracks.io.file.exporter.ExportActivity.onCreate(ExportActivity.java:63)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.Activity.performCreate(Activity.java:7144)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.Activity.performCreate(Activity.java:7135)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	... 11 more
01-20 03:52:41.423 E/AndroidRuntime(31594): Caused by: java.lang.NoSuchMethodException: <init> []
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at java.lang.Class.getConstructor0(Class.java:2327)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at java.lang.Class.getConstructor(Class.java:1725)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:523)
01-20 03:52:41.423 E/AndroidRuntime(31594): 	... 22 more
```

**Comment by dennisguse** [comment]
Issue was introduced in 8b11e1d611f502e0f1823b17cb3db12dac67e22b
