### ISSUE TITLE
App crashes after clicking on the map icon

### ISSUE THREAD

**Issue by IronJaeger** [OpenTracksApp/OpenTracks#1300]
### App information
* ID: de.dennisguse.opentracks
* Version: 4926 v4.0.1

### Device information
* Brand: HUAWEI
* Device: HWH1711-Q
* Model: H1711
* Id: HUAWEIH1711
* Product: H1711

### Firmware
* SDK: 24
* Release: 7.0
* Incremental: C07B130

### Cause of error
```java
Exception in thread "main": android.content.ActivityNotFoundException: No Activity found to handle Intent { act=Intent.OpenTracks-Dashboard flg=0x1 clip={text/uri-list U:content://de.dennisguse.opentracks.content/tracks/2 ...} (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1854)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1544)
	at android.app.Activity.startActivityForResult(Activity.java:4391)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:4335)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:4697)
	at android.app.Activity.startActivity(Activity.java:4665)
	at de.dennisguse.opentracks.util.IntentDashboardUtils.startDashboard(IntentDashboardUtils.java:176)
	at de.dennisguse.opentracks.util.IntentDashboardUtils.onFormatSelected(IntentDashboardUtils.java:124)
	at de.dennisguse.opentracks.util.IntentDashboardUtils.showTrackOnMap(IntentDashboardUtils.java:103)
	at de.dennisguse.opentracks.TrackRecordedActivity.onOptionsItemSelected(TrackRecordedActivity.java:182)
	at android.app.Activity.onMenuItemSelected(Activity.java:3356)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:221)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:5647)
	at android.view.View$PerformClick.run(View.java:22479)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6581)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by dennisguse** [comment]
Thx. Fix is in tomorrow' nightly
