### ISSUE TITLE
Bug: Window leaked exception

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#138]
Some dialog in TrackListActivity does not seem to be properly dismissed.

```
01-31 16:50:34.115 12370 12370 E WindowManager: android.view.WindowLeaked: Activity de.dennisguse.opentracks.TrackListActivity has leaked window android.widget.PopupWindow$PopupDecorView{466d61c V.E...... R.....ID 0,0-588,288} that was originally added here
01-31 16:50:34.115 12370 12370 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:511)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1434)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1284)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at androidx.appcompat.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java:77)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at androidx.core.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:69)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at androidx.appcompat.widget.ListPopupWindow.show(ListPopupWindow.java:755)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at androidx.appcompat.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:181)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at androidx.appcompat.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:208)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at androidx.appcompat.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:290)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at androidx.appcompat.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:177)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at androidx.appcompat.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:797)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:873)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at android.os.Looper.loop(Looper.java:193)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-31 16:50:34.115 12370 12370 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by dennisguse** [comment]
Tracks are loaded via CursorLoader, but for each track then the waypoint count is loaded in the UI thread...

I guess, the best approach is to get all this information from via the CursorLoader directly, i.e., changing the ContentProvider.

**Comment by dennisguse** [comment]
Don't know what triggered this issue and cannot reproduce it.
Might be gone :)
