### ISSUE TITLE
Crash on voice announcement

### ISSUE THREAD

**Issue by kmantel** [OpenTracksApp/OpenTracks#1626]
**Describe the bug**
Crash on voice announcement during activity when preferred units set to Imperial (mi, m). It looks like `IMPERIAL_METER` is not handled in https://github.com/OpenTracksApp/OpenTracks/blob/a4ec68def617eb4ef241079677ee5df5bd7d48b8/src/main/java/de/dennisguse/opentracks/services/announcement/VoiceAnnouncementUtils.java#L47

### App information
* ID: de.dennisguse.opentracks
* Version: 5286 v4.6.0

### Firmware
* SDK: 33
* Release: 13

### Cause of error
```java
Exception in thread "main": java.lang.RuntimeException: Not implemented
	at de.dennisguse.opentracks.services.announcement.VoiceAnnouncementUtils.getAnnouncement(VoiceAnnouncementUtils.java:69)
	at de.dennisguse.opentracks.services.announcement.VoiceAnnouncement.announce(VoiceAnnouncement.java:185)
	at de.dennisguse.opentracks.services.announcement.VoiceAnnouncementManager.update(VoiceAnnouncementManager.java:104)
	at de.dennisguse.opentracks.services.TrackRecordingService.updateRecordingDataWhileRecording(TrackRecordingService.java:330)
	at de.dennisguse.opentracks.services.TrackRecordingService.-$$Nest$mupdateRecordingDataWhileRecording(Unknown Source:0)
	at de.dennisguse.opentracks.services.TrackRecordingService$1.run(TrackRecordingService.java:70)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by dennisguse** [comment]
@kmantel could you create a pull request for this problem?
