### ISSUE TITLE
Setting of Bluetooth Sensors causes crash

### ISSUE THREAD

**Issue by khao-soi** [OpenTracksApp/OpenTracks#1637]
**Describe the bug**
App crashes when clicking on Heart Rate and other stuff

**To Reproduce**
1. Have no bluetooth device connected
2. Go to Settings - Bluetooth Sensors
3. Click on Heart Reate, Cadence or Power
4. See error below

**Technical information**
 - Device: OnePlus 8T
 - OS: LineageOS 20.0
 - OpenTracks version: 4.6.1 F-Droid

**Error:**

### App information
* ID: de.dennisguse.opentracks
* Version: 5289 v4.6.1

### Device information
* Brand: OnePlus
* Device: OnePlus8T
* Model: KB2003
* Id: TQ3A.230605.012
* Product: OnePlus8T

### Firmware
* SDK: 33
* Release: 13
* Incremental: eng.root.20230706.194344

### Cause of error
```java
Exception in thread "main": java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for AttributionSource { uid = 10187, packageName = de.dennisguse.opentracks, attributionTag = null, token = android.os.BinderProxy@f6097c5, next = null }: AdapterService isDiscovering
	at com.android.bluetooth.Utils.checkPermissionForDataDelivery(Utils.java:486)
	at com.android.bluetooth.Utils.checkScanPermissionForDataDelivery(Utils.java:545)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.isDiscovering(AdapterService.java:2105)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.isDiscovering(AdapterService.java:2096)
	at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:613)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1244)
```

**Comment by khao-soi** [comment]
> Was the permission initially granted and then later on revoked?

I don't think so, but I can guarantee that. Still, the app shouldn't crash here =)

**Comment by khao-soi** [comment]
I could add handling for this, I guess. Since I already have the scenario.
