### ISSUE TITLE
Crash when trying to export workouts

### ISSUE THREAD

**Issue by RugeljGG** [OpenTracksApp/OpenTracks#1648]
Probably related to https://github.com/OpenTracksApp/OpenTracks/issues/1647. App crashes when I try to export all workouts.

### App information
* ID: de.dennisguse.opentracks
* Version: 5289 v4.6.1

### Device information
* Brand: samsung
* Device: r0s
* Model: SM-S901B
* Id: TP1A.220624.014
* Product: r0sxeea

### Firmware
* SDK: 33
* Release: 13
* Incremental: S901BXXS6CWF6

### Cause of error
```java
Exception in thread "AsyncTask #2": java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List de.dennisguse.opentracks.io.file.exporter.ExportTask.getTrackIds()' on a null object reference
	at de.dennisguse.opentracks.util.ExportUtils.exportTrack(ExportUtils.java:64)
	at de.dennisguse.opentracks.io.file.exporter.ExportService.onHandleWork(ExportService.java:54)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

**Comment by dennisguse** [comment]
All tracks into one file or all tracks into separate files?

**Comment by dennisguse** [comment]
Actually can you reproduce this repeatedly or was a "happened once"?

**Comment by RugeljGG** [comment]
Sorry for the late response. Crash happens every time, both when exporting one per file and when exporting in separate files. But after testing it now, it's not always the same error. 

To add additional context, when I posted the error message, I wasn't able to export in any of the available format, app kept crashing (although I'm not sure if error message was always the same). After you asked for export of the problematic track, I've tried it again and export in both KML and KMZ suddenly worked. Now I can't export anything again, not matter which file format I choose. I'll play around later today and try to reproduce the steps to make this happen (and post error messages).

**Comment by RugeljGG** [comment]
Got some additional info - after rebooting phone, all exports but gpx work. However, after I try to export in GPX (and all crashes), export stops working for all file formats (both single file and separate files) - either it crashes or just hangs up (left it for an hour once and it didn't finish). Example error after trying to export all in separate files as KMZ:

### App information
* ID: de.dennisguse.opentracks
* Version: 5289 v4.6.1

### Device information
* Brand: samsung
* Device: r0s
* Model: SM-S901B
* Id: TP1A.220624.014
* Product: r0sxeea

### Firmware
* SDK: 33
* Release: 13
* Incremental: S901BXXS6CWF6

### Cause of error
```java
Exception in thread "AsyncTask #2": java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
	at de.dennisguse.opentracks.data.models.TrackPoint.getLatitude(TrackPoint.java:162)
	at de.dennisguse.opentracks.io.file.exporter.GPXTrackExporter.writeTrackPoint(GPXTrackExporter.java:311)
	at de.dennisguse.opentracks.io.file.exporter.GPXTrackExporter.writeTrackPoints(GPXTrackExporter.java:154)
	at de.dennisguse.opentracks.io.file.exporter.GPXTrackExporter.writeTrack(GPXTrackExporter.java:111)
	at de.dennisguse.opentracks.util.ExportUtils.exportTrack(ExportUtils.java:80)
	at de.dennisguse.opentracks.io.file.exporter.ExportService.onHandleWork(ExportService.java:54)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

**Comment by dennisguse** [comment]
Hopefully also gone due to  #1647.
