### ISSUE TITLE
latest nighty bug

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1668]
Turned on my phone hours after i last used open tracks nightly and this was shown.
No idea why. I had not used open tracks for maybe 10 hours. I think i used the phone for a few other things during the day but not much

### App information
* ID: de.dennisguse.opentracks.nightly
* Version: 5362 v4.8.0

### Device information
* Brand: Blackview
* Device: BV9800Pro
* Model: BV9800Pro
* Id: PPR1.180610.011
* Product: BV9800Pro_EEA

### Firmware
* SDK: 28
* Release: 9
* Incremental: root.20200814.112030

### Cause of error
```java
Exception in thread "main": java.lang.NullPointerException: Attempt to invoke virtual method 'void de.dennisguse.opentracks.services.TrackRecordingServiceNotificationManager.updateContent(java.lang.String)' on a null object reference
	at de.dennisguse.opentracks.services.TrackRecordingService.newGpsStatus(TrackRecordingService.java:247)
	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.sendGpsStatus(TrackPointCreator.java:151)
	at de.dennisguse.opentracks.services.handlers.GPSManager.onGpsStatusChanged(GPSManager.java:169)
	at de.dennisguse.opentracks.services.handlers.GpsStatusManager.setGpsStatus(GpsStatusManager.java:165)
	at de.dennisguse.opentracks.services.handlers.GpsStatusManager.determineGpsStatusOnTrackpoint(GpsStatusManager.java:111)
	at de.dennisguse.opentracks.services.handlers.GpsStatusManager.onNewTrackPoint(GpsStatusManager.java:91)
	at de.dennisguse.opentracks.services.handlers.GPSManager.onLocationChanged(GPSManager.java:117)
	at androidx.core.location.LocationManagerCompat$LocationListenerTransport.lambda$onLocationChanged$0$androidx-core-location-LocationManagerCompat$LocationListenerTransport(LocationManagerCompat.java:679)
	at androidx.core.location.LocationManagerCompat$LocationListenerTransport$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by dennisguse** [comment]
Also happened to me today (Android 11) - although it shouldn't.
I will re-add the race condition handling and print some logs instead of crashing.

The problem is related to `LocationManagerCompat.removeUpdates()`, but I don't know exactly why this is not working as expected.
