### ISSUE TITLE
MI5 band crashes opentracks at recording start

### ISSUE THREAD

**Issue by Geier0815** [OpenTracksApp/OpenTracks#1792]
**Describe the bug**
With the nightly 5566 v4.9.8-2-g47ceb297c I've choose the MI5 band as HR source, changed the layout to show HR, started the recording which directly chrased, error message follows.
Gadgetbridge were not started.
In former times the MI5 band works without any problems. Last time I've used it were end of september.

**To Reproduce**
1. Install the nightly build
2. choose the MI5 band as heartrate source
3. change the standard layout to show heartrate
4. start a recording

### App information
* ID: de.dennisguse.opentracks.nightly
* Version: 5566 v4.9.8-2-g47ceb297c

### Device information
* Brand: Nokia
* Device: PAN_sprout
* Model: Nokia 4.2
* Id: RKQ1.200928.002
* Product: Panther_00EEA

### Firmware
* SDK: 30
* Release: 11
* Incremental: 00EEA_3_24B

### Cause of error
```java
Exception in thread "main": java.lang.RuntimeException: SensorManager cannot be started twice; stop first.
at de.dennisguse.opentracks.sensors.SensorManager.start(SensorManager.java:61)
at de.dennisguse.opentracks.services.handlers.TrackPointCreator.start(TrackPointCreator.java:47)
at de.dennisguse.opentracks.services.TrackRecordingService.startSensors(TrackRecordingService.java:203)
at de.dennisguse.opentracks.services.TrackRecordingService.startRecording(TrackRecordingService.java:190)
at de.dennisguse.opentracks.services.TrackRecordingService.startNewTrack(TrackRecordingService.java:171)
at de.dennisguse.opentracks.TrackListActivity.lambda$onCreate$5(TrackListActivity.java:187)
at de.dennisguse.opentracks.TrackListActivity.$r8$lambda$9VATjDTlXeRwAYrK9Lb8GzlwA8U(Unknown Source:0)
at de.dennisguse.opentracks.TrackListActivity$$ExternalSyntheticLambda8.onConnected(Unknown Source:2)
at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.setTrackRecordingService(TrackRecordingServiceConnection.java:147)
at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.onServiceConnected(TrackRecordingServiceConnection.java:162)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1978)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2010)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7697)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by dennisguse** [comment]
OpenTracks is still broken - just the actual problem is now shown. 

This error happens with the second start of a recording. 
After the first recording, you have to "force close" OpenTracks via the systems manager. 

PS problem is not related to the heart rate sensor. It was just showing the effect.
