### ISSUE TITLE
crash on start button 

### ISSUE THREAD

**Issue by shanker11** [OpenTracksApp/OpenTracks#1795]
### App information
* ID: de.dennisguse.opentracks.nightly
* Version: 5566 v4.9.8-2-g47ceb297c

### Device information
* Brand: samsung
* Device: m23xq
* Model: SM-E236B
* Id: TP1A.220624.014
* Product: m23xqdd

### Firmware
* SDK: 33
* Release: 13
* Incremental: E236BXXU4CWI1

### Cause of error
```java
Exception in thread "main": java.lang.RuntimeException: SensorManager cannot be started twice; stop first.
	at de.dennisguse.opentracks.sensors.SensorManager.start(SensorManager.java:61)
	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.start(TrackPointCreator.java:47)
	at de.dennisguse.opentracks.services.TrackRecordingService.startSensors(TrackRecordingService.java:203)
	at de.dennisguse.opentracks.services.TrackRecordingService.startRecording(TrackRecordingService.java:190)
	at de.dennisguse.opentracks.services.TrackRecordingService.startNewTrack(TrackRecordingService.java:171)
	at de.dennisguse.opentracks.TrackListActivity.lambda$onCreate$5(TrackListActivity.java:187)
	at de.dennisguse.opentracks.TrackListActivity.$r8$lambda$9VATjDTlXeRwAYrK9Lb8GzlwA8U(Unknown Source:0)
	at de.dennisguse.opentracks.TrackListActivity$$ExternalSyntheticLambda8.onConnected(Unknown Source:2)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.setTrackRecordingService(TrackRecordingServiceConnection.java:147)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.onServiceConnected(TrackRecordingServiceConnection.java:162)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2348)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2381)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by dennisguse** [comment]
Should be fixed by #1793.
Nightly will be available in a few minutes.
