### ISSUE TITLE
Instant crash when trying to record

### ISSUE THREAD

**Issue by jan0sch** [OpenTracksApp/OpenTracks#1867]
**Describe the bug**
It crashes whenever I press on the record button.

**To Reproduce**
1. Start OpenTracks
2. Click on the record button

**Technical information**
 - Device: [e.g. Nexus 7 (2013)]
 - OS: [e.g. LineageOS 15.1]
 - OpenTracks version: [e.g. v3.2.4]
 - OpenTracks commit id (only for nightly builds): [e.g. 4b333bb]

### Cause of error
```java
Exception in thread "main": java.lang.RuntimeException: Android14: Please grant permissions LOCATION and NEARBY DEVICES (manually)
	at de.dennisguse.opentracks.services.TrackRecordingService.startSensors(TrackRecordingService.java:218)
	at de.dennisguse.opentracks.services.TrackRecordingService.startRecording(TrackRecordingService.java:194)
	at de.dennisguse.opentracks.services.TrackRecordingService.startNewTrack(TrackRecordingService.java:174)
	at de.dennisguse.opentracks.TrackListActivity.lambda$onCreate$6(TrackListActivity.java:182)
	at de.dennisguse.opentracks.TrackListActivity.$r8$lambda$sfL1wLWtkeS4x8K11Too1HQMWNU(Unknown Source:0)
	at de.dennisguse.opentracks.TrackListActivity$$ExternalSyntheticLambda2.onConnected(Unknown Source:2)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.lambda$execute$1(TrackRecordingServiceConnection.java:139)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection$$ExternalSyntheticLambda0.onConnected(Unknown Source:4)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.setTrackRecordingService(TrackRecordingServiceConnection.java:120)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.-$$Nest$msetTrackRecordingService(Unknown Source:0)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection$1.onServiceConnected(TrackRecordingServiceConnection.java:58)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2207)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2240)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by jan0sch** [comment]
After granting the permission "near devices" manually it seems to work.
