### ISSUE TITLE
Crash on start records after click on pre run GPS icon

### ISSUE THREAD

**Issue by FHenry** [OpenTracksApp/OpenTracks#1887]
**Describe the bug**
On the bottom of the screen start the GPS 
Then when the GPS icon is stable (or not) click on start record

But start the records directly work fine

**To Reproduce**
1. Check describe the bug

### App information
* ID: de.dennisguse.opentracks.playstore
* Version: 5730 v4.12.1-PlayStore

### Device information
* Brand: Xiaomi
* Device: tucana
* Model: Mi Note 10
* Id: QKQ1.190825.002
* Product: tucana_eea

### Firmware
* SDK: 29
* Release: 10
* Incremental: V12.0.1.0.QFDEUXM

### Cause of error
```java
Exception in thread "main": java.lang.RuntimeException: SensorManager cannot be started twice; stop first.
	at de.dennisguse.opentracks.sensors.SensorManager.start(SensorManager.java:67)
	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.start(TrackPointCreator.java:47)
	at de.dennisguse.opentracks.services.TrackRecordingService.startSensors(TrackRecordingService.java:211)
	at de.dennisguse.opentracks.services.TrackRecordingService.startRecording(TrackRecordingService.java:192)
	at de.dennisguse.opentracks.services.TrackRecordingService.startNewTrack(TrackRecordingService.java:172)
	at de.dennisguse.opentracks.TrackListActivity.lambda$onCreate$6(TrackListActivity.java:184)
	at de.dennisguse.opentracks.TrackListActivity.$r8$lambda$zZE3EWVw__RyZbejvjKvasa-kHM(Unknown Source:0)
	at de.dennisguse.opentracks.TrackListActivity$$ExternalSyntheticLambda4.onConnected(D8$$SyntheticClass:0)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.lambda$executeForeground$2(TrackRecordingServiceConnection.java:169)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection$$ExternalSyntheticLambda0.onConnected(D8$$SyntheticClass:0)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.setTrackRecordingService(TrackRecordingServiceConnection.java:135)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.-$$Nest$msetTrackRecordingService(Unknown Source:0)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection$1.onServiceConnected(TrackRecordingServiceConnection.java:62)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1956)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1988)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7584)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by dennisguse** [comment]
Released as v4.12.2
