### ISSUE TITLE
Crash on run start (after aquiring GPS lock)

### ISSUE THREAD

**Issue by 5c077m4n** [OpenTracksApp/OpenTracks#1890]
### App information
* ID: de.dennisguse.opentracks
* Version: 5730 v4.12.1

### Device information
* Brand: samsung
* Device: beyond0lte
* Model: SM-G970F
* Id: SQ3A.220705.004
* Product: lineage_beyond0lte

### Firmware
* SDK: 32
* Release: 12
* Incremental: eng.root.20240111.181135

### Cause of error
```java
Exception in thread "main": java.lang.RuntimeException: SensorManager cannot be started twice; stop first.
	at de.dennisguse.opentracks.sensors.SensorManager.start(SensorManager.java:67)
	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.start(TrackPointCreator.java:47)
	at de.dennisguse.opentracks.services.TrackRecordingService.startSensors(TrackRecordingService.java:211)
	at de.dennisguse.opentracks.services.TrackRecordingService.startRecording(TrackRecordingService.java:192)
	at de.dennisguse.opentracks.services.TrackRecordingService.startNewTrack(TrackRecordingService.java:172)
	at de.dennisguse.opentracks.TrackListActivity.lambda$onCreate$6(TrackListActivity.java:184)
	at de.dennisguse.opentracks.TrackListActivity.$r8$lambda$zZE3EWVw__RyZbejvjKvasa-kHM(Unknown Source:0)
	at de.dennisguse.opentracks.TrackListActivity$$ExternalSyntheticLambda4.onConnected(D8$$SyntheticClass:0)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.lambda$executeForeground$2(TrackRecordingServiceConnection.java:169)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection$$ExternalSyntheticLambda0.onConnected(D8$$SyntheticClass:0)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.setTrackRecordingService(TrackRecordingServiceConnection.java:135)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.-$$Nest$msetTrackRecordingService(Unknown Source:0)
	at de.dennisguse.opentracks.services.TrackRecordingServiceConnection$1.onServiceConnected(TrackRecordingServiceConnection.java:62)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by 5c077m4n** [comment]
Thank you very much 🙏🏼
