### ISSUE TITLE
App crashes when trying to delete marker

### ISSUE THREAD

**Issue by dmlls** [OpenTracksApp/OpenTracks#1915]
### Steps to reproduce
1. Select recording with markers.
2. Go to markers.
3. Select marker and try to delete it.
5. App crashes.

### App information
* ID: de.dennisguse.opentracks
* Version: 5753 v4.12.3

### Device information
* Brand: Xiaomi
* Device: beryllium
* Model: POCO F1
* Id: TQ3A.230901.001
* Product: beryllium

### Firmware
* SDK: 33
* Release: 13
* Incremental: eng.root.20240507.191957

### Cause of error
```java
Exception in thread "main": java.lang.ClassCastException: de.dennisguse.opentracks.ui.markers.MarkerListActivity@289585 must implement DeleteMarkerCaller
	at de.dennisguse.opentracks.ui.markers.DeleteMarkerDialogFragment.onAttach(DeleteMarkerDialogFragment.java:60)
	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by Anke** [comment]
Same here:

`### App information
* ID: de.dennisguse.opentracks
* Version: 5753 v4.12.3

### Device information
* Brand: google
* Device: husky
* Model: Pixel 8 Pro
* Id: xxx
* Product: husky

### Firmware
* SDK: 34
* Release: 14
* Incremental: 11677807

### Cause of error
```java
Exception in thread "main": java.lang.ClassCastException: de.dennisguse.opentracks.ui.markers.MarkerListActivity@4ba66ee must implement DeleteMarkerCaller
	at de.dennisguse.opentracks.ui.markers.DeleteMarkerDialogFragment.onAttach(DeleteMarkerDialogFragment.java:60)
	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
````
