### ISSUE TITLE
Crashes when creating a waypoint while device is locked

### ISSUE THREAD

**Issue by Latzze** [OpenTracksApp/OpenTracks#1927]
**Bug describtion**
When locking the device by presaing the powerbutton or by waiting until it locks automatically and then turning the screen on the opentracs interface is shown but the device is othervice locked. In this state trying to create a waypoint leads to errormessage and the recording stops.

**To Reproduce**
1. Start recording a new track.
2. Lock your device manually or wait until locked automatically.
3. Power the screen on.
4. Click "new waypoint"

**Log message that I got without device and app info**
```java
Exception in thread "main": java.lang.NullPointerException: Attempt to invoke virtual method 'de.dennisguse.opentracks.data.models.Marker$Id de.dennisguse.opentracks.data.models.Marker.getId()' on a null object reference
	at de.dennisguse.opentracks.ui.markers.MarkerEditActivity.onSaveInstanceState(MarkerEditActivity.java:226)
	at android.app.Activity.performSaveInstanceState(Activity.java:2260)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1563)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6503)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5849)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5809)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5880)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)




**Technical information**
 - ID: de.dennisguse.opentracks
 - Version: 5788 v4.12.4
 - Device: Samsung galaxy a71
 - OS: default

**Comment by dennisguse** [comment]
This was fixed by implementing this 389c4bed9615fbdf25e242dcd482f7a8b6fbb3bd
