### ISSUE TITLE
Export not possible

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#252]
Got a bug report via mail.

**Describe the bug**
```
06-07 03:06:23.312 E/AndroidRuntime( 8362): Process: de.dennisguse.opentracks, PID: 8362
06-07 03:06:23.312 E/AndroidRuntime( 8362): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.dennisguse.opentracks/de.dennisguse.opentracks.io.file.exporter.ExportActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment de.dennisguse.opentracks.fragments.FileTypeDialogF
ragment: could not find Fragment constructor
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5279)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5187)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.os.Looper.loop(Looper.java:214)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at java.lang.reflect.Method.invoke(Native Method)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
06-07 03:06:23.312 E/AndroidRuntime( 8362): Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment de.dennisguse.opentracks.fragments.FileTypeDialogFragment: could not find Fragment constructor
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:538)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at androidx.fragment.app.FragmentManagerImpl$6.instantiate(FragmentManagerImpl.java:2851)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:85)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:2488)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:195)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:288)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at de.dennisguse.opentracks.io.file.exporter.ExportActivity.onCreate(ExportActivity.java:64)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.Activity.performCreate(Activity.java:7824)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.Activity.performCreate(Activity.java:7813)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	... 13 more
06-07 03:06:23.312 E/AndroidRuntime( 8362): Caused by: java.lang.NoSuchMethodException: de.dennisguse.opentracks.fragments.FileTypeDialogFragment.<init> []
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at java.lang.Class.getConstructor0(Class.java:2332)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at java.lang.Class.getConstructor(Class.java:1728)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:523)
06-07 03:06:23.312 E/AndroidRuntime( 8362): 	... 24 more
```

**To Reproduce**
1. Go to Settings
2. Click on 'Export all'
3. See error

**Technical information**
 - OS: lineage-17.1-20200604-nightly-kuntao
 - Version since 3.3.1

**Comment by dennisguse** [comment]
Was actually reported for v3.7.4 again although FileTypeDialogFragment was removed in this version.

**Comment by dennisguse** [comment]
I got no more info about this issue.
Please re-open if it is till a problem.
