### ISSUE TITLE
App didn't open on Android 10

### ISSUE THREAD

**Issue by mawenzy** [OpenTracksApp/OpenTracks#422]
**The bug**
App doesn't open after update to newest version, Android shows message 'App repeatedly gets closed'

**Clearing the storage fixed the issue**, but I'm filing anyway, because clearing the storage doesn't feel right. Maybe the following crash stacktrace can be of some use.

**To Reproduce**
Tried to open the app :)

```bash
[me@localhost ~]$ adb logcat guse.opentrack:E AndroidRuntime:E *:S
--------- beginning of main
--------- beginning of system
09-09 10:44:35.332 30513 30513 E guse.opentrack: Unknown bits set in runtime_flags: 0x20000
09-09 10:44:35.334 30513 30513 E guse.opentrack: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of crash
09-09 10:44:35.373 30513 30513 E AndroidRuntime: FATAL EXCEPTION: main
09-09 10:44:35.373 30513 30513 E AndroidRuntime: Process: de.dennisguse.opentracks, PID: 30513
09-09 10:44:35.373 30513 30513 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider de.dennisguse.opentracks.content.provider.ShareContentProvider: java.lang.RuntimeException: Not supported
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7305)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6765)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6615)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:232)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1953)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7697)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: Caused by: java.lang.RuntimeException: Not supported
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at de.dennisguse.opentracks.content.data.Track$Id.toString(Track.java:156)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at java.lang.String.valueOf(String.java:2924)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at de.dennisguse.opentracks.content.provider.CustomSQLiteOpenHelper.upgradeFrom25to26(CustomSQLiteOpenHelper.java:169)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at de.dennisguse.opentracks.content.provider.CustomSQLiteOpenHelper.onUpgrade(CustomSQLiteOpenHelper.java:71)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:417)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at de.dennisguse.opentracks.content.provider.CustomContentProvider.onCreate(CustomContentProvider.java:84)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at de.dennisguse.opentracks.content.provider.CustomContentProvider.onCreate(CustomContentProvider.java:71)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2154)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2128)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at de.dennisguse.opentracks.content.provider.ShareContentProvider.attachInfo(ShareContentProvider.java:123)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7294)
09-09 10:44:35.373 30513 30513 E AndroidRuntime: 	... 10 more
```
**Technical information**

```bash
[me@localhost ~]$ adb devices -l
List of devices attached
b6f09ad2               device usb:1-2 product:OnePlus5T model:ONEPLUS_A5010 device:OnePlus5T transport_id:11

[me@localhost ~]$ adb shell getprop ro.build.version.sdk
29
[me@localhost ~]$ adb shell getprop ro.build.version.release
10
```
 - Device: [OnePlus 5T]
 - OS: [Android 10]
 - Build-Number: [ONEPLUS_A5010_43_200601]
 - Version [v3.9.5] (installed through F-Droid)

**Comment by dennisguse** [comment]
The underlying reason is that you updated from a pre v3.9.X version and we never to tested this.
@rgmf thanks.
