### ISSUE TITLE
Track import result not shown if ImportActivity not visible (anymore)

### ISSUE THREAD

**Issue by pstorch** [OpenTracksApp/OpenTracks#471]
If the track import takes longer and the phone turns of the display, the result dialog crashes:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.dennisguse.opentracks.debug, PID: 20559
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1691)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1731)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:181)
        at de.dennisguse.opentracks.fragments.ImportFinishedDialogFragment.showDialog(ImportFinishedDialogFragment.java:50)
        at de.dennisguse.opentracks.io.file.importer.ImportActivity.lambda$onImportFinished$0$ImportActivity(ImportActivity.java:70)
        at de.dennisguse.opentracks.io.file.importer.-$$Lambda$ImportActivity$plu8T-FPTkG1j8B2BGV237dSfYM.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

Would it be better to replace this dialog by a regular screen as implemented in the ExportActivity?

**Comment by rgmf** [comment]
@pstorch this would be a logical step. In fact, I'd like to do it this weekend (we'll see).

My intention is doing the same we have now in ExportActivity with a summary:
- Imported tracks.
- Tracks that already exists.
- Errors... with the error message triggered.

If you don't mind I take this issue because I think it will be very similar to ExportActivity.
