### ISSUE TITLE
For release v3.16.0: fix test

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#670]
```
de.dennisguse.opentracks.io.file.importer.ExportImportTest > kml_with_trackdetail[test(AVD) - 10] FAILED 
	java.lang.AssertionError: expected:<15.0> but was:<111167.9296875>
	at org.junit.Assert.fail(Assert.java:88)
```

**Comment by dennisguse** [comment]
Sounds like the TrackStatisticsUpdater is not reset on segment end.
I guess it is in the KML importer.

**Comment by dennisguse** [comment]
Somehow this is flacky...

**Comment by dennisguse** [comment]
We also got:
```
de.dennisguse.opentracks.io.file.importer.ExportImportTest > kml_with_trackdetail[test(AVD) - 10] FAILED 
	java.lang.AssertionError: expected:<30.0> but was:<222335.859375>
	at org.junit.Assert.fail(Assert.java:88)
```

Current hypothesis: the track is somehow not deleted properly between tests.
The tests _should_ be deterministic.....
