### ISSUE TITLE
v3.17.0/v3.17.1: crash while using voice announcements

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#721]
Due to #719, using voice announcements leads to a crash.

Introduced in v3.17.0 and made worse in v3.17.1.

```
-17 15:49:15.315 30148 30648 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'j$.time.Duration de.dennisguse.opentracks.content.data.Speed.toPace(boolean)' on a null object reference
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at de.dennisguse.opentracks.util.AnnouncementUtils.getAnnouncement(AnnouncementUtils.java:46)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at de.dennisguse.opentracks.services.tasks.AnnouncementPeriodicTask.announce(AnnouncementPeriodicTask.java:199)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at de.dennisguse.opentracks.services.tasks.AnnouncementPeriodicTask.run(AnnouncementPeriodicTask.java:151)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at de.dennisguse.opentracks.services.tasks.PeriodicTaskExecutor.update(PeriodicTaskExecutor.java:134)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingService.insertTrackPoint(TrackRecordingService.java:618)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingService.insertTrackPointIfNewer(TrackRecordingService.java:586)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingService.newTrackPoint(TrackRecordingService.java:526)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at de.dennisguse.opentracks.services.handlers.HandlerServer.lambda$sendTrackPoint$0$HandlerServer(HandlerServer.java:59)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at de.dennisguse.opentracks.services.handlers.-$$Lambda$HandlerServer$u7UpyDYRGPit7CRfg_glQph5Wm8.run(Unknown Source:6)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-17 15:49:15.315 30148 30648 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
04-17 15:49:50.249 30685 30783 E AndroidRuntime: Process: de.dennisguse.opentracks, PID: 30685
04-17 15:49:50.249 30685 30783 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'j$.time.Duration de.dennisguse.opentracks.content.data.Speed.toPace(boolean)' on a null object reference
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at de.dennisguse.opentracks.util.AnnouncementUtils.getAnnouncement(AnnouncementUtils.java:46)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at de.dennisguse.opentracks.services.tasks.AnnouncementPeriodicTask.announce(AnnouncementPeriodicTask.java:199)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at de.dennisguse.opentracks.services.tasks.AnnouncementPeriodicTask.run(AnnouncementPeriodicTask.java:151)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at de.dennisguse.opentracks.services.tasks.PeriodicTaskExecutor.update(PeriodicTaskExecutor.java:134)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingService.insertTrackPoint(TrackRecordingService.java:618)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingService.insertTrackPointIfNewer(TrackRecordingService.java:586)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at de.dennisguse.opentracks.services.TrackRecordingService.newTrackPoint(TrackRecordingService.java:526)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at de.dennisguse.opentracks.services.handlers.HandlerServer.lambda$sendTrackPoint$0$HandlerServer(HandlerServer.java:59)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at de.dennisguse.opentracks.services.handlers.-$$Lambda$HandlerServer$u7UpyDYRGPit7CRfg_glQph5Wm8.run(Unknown Source:6)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-17 15:49:50.249 30685 30783 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by dennisguse** [comment]
Released as v3.17.3
