### ISSUE TITLE
(not yet released) NPE when using no speed sensor

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#815]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean de.dennisguse.opentracks.content.data.Distance.lessThan(de.dennisguse.opentracks.content.data.Distance)' on a null object reference
at de.dennisguse.opentracks.stats.TrackStatisticsUpdater.addTrackPoint(TrackStatisticsUpdater.java:178)
at de.dennisguse.opentracks.services.TrackRecordingService.updateRecordingDataWhileRecording(TrackRecordingService.java:766)
at de.dennisguse.opentracks.services.TrackRecordingService.access$000(TrackRecordingService.java:75)
at de.dennisguse.opentracks.services.TrackRecordingService$1.run(TrackRecordingService.java:94)
```

Best guess, introduced in https://github.com/OpenTracksApp/OpenTracks/commit/2f0449c4209633417d798b7b0f108a99f46956ad

**Comment by dennisguse** [comment]
Fixed in https://github.com/OpenTracksApp/OpenTracks/commit/47a340578f954f8adc3383d83b4015d8c6e0bb25
