### ISSUE TITLE
FATAL EXCEPTION: AsyncTask 🤪

### ISSUE THREAD

**Issue by vsevjednom-cz** [OpenTracksApp/OpenTracks#847]
**Describe the bug**
I found this bug accidentally 🙃. It's not an important error. But it can happen sometimes 🤖.

**To Reproduce**
1. Start tracking.
2. Go to the list.
3. Mark current activity.
4. Tap to the menu and to the `Delete` (`menu_delete`).
5. Confirm it.
6. `FATAL EXCEPTION`

**Technical information**
 - Device: Honor KSA-LX9
 - OS: Android 9.1.0

```
E/pentracks.debu: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: de.dennisguse.opentracks.debug, PID: 27042
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:355)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.UUID de.dennisguse.opentracks.content.data.Track.getUuid()' on a null object reference
        at de.dennisguse.opentracks.util.ExportUtils.getExportFileNameForTrack(ExportUtils.java:104)
        at de.dennisguse.opentracks.util.ExportUtils.getExportDocumentFileUri(ExportUtils.java:92)
        at de.dennisguse.opentracks.util.ExportUtils.exportTrack(ExportUtils.java:44)
        at de.dennisguse.opentracks.io.file.exporter.ExportService.onHandleWork(ExportService.java:51)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
```

**Comment by rgmf** [comment]
Yes, I can reproduce it. With post-export option on when you delete the current recording track OT crashes.
Good catch @vsevjednom-cz
