### ISSUE TITLE
v3.19.0: Null Pointer Exception: BluetoothRemoteSensorManager.reset()

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#901]
**Describe the bug**
I stumble upon this error testing current main branch. It's triggered when you Resume a recorded Track.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void de.dennisguse.opentracks.services.sensors.BluetoothRemoteSensorManager.reset()' on a null object reference
        at de.dennisguse.opentracks.services.handlers.TrackPointCreator.resetSensorData(TrackPointCreator.java:75)
        at de.dennisguse.opentracks.services.TrackRecordingService.resumeTrack(TrackRecordingService.java:242)
        at de.dennisguse.opentracks.TrackRecordingActivity$1.run(TrackRecordingActivity.java:86)
        at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.setTrackRecordingService(TrackRecordingServiceConnection.java:136)
        at de.dennisguse.opentracks.services.TrackRecordingServiceConnection.onServiceConnected(TrackRecordingServiceConnection.java:148)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**To Reproduce**
1. Go to list of tracks.
2. Click on a track.
3. Click on menu and select "Resume track".
4. See errorr.

**Technical information**
 - Device: any.
 - OS: any.
 - Version: on current main branch.

**Comment by dennisguse** [comment]
Also reported via PlayStore.
