### ISSUE TITLE
Crashes on Intervals tab

### ISSUE THREAD

**Issue by FTno** [OpenTracksApp/OpenTracks#996]
I installed OpenTracks on an old Samsung phone (Galaxy S7) with Android 7 and here the app crashes when opening a saved track and pressing the Intervals tab.

v3.20.2

**Comment by FTno** [comment]
Exported both tracks (old and new), deleted them from the list, imported them. The new is fine, the old same issue.


Crash report:

```
FATAL EXCEPTION: pool-1-thread-1
Process: de.dennisguse.opentracks, PID: 5644
java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
	at de.dennisguse.opentracks.viewmodels.IntervalStatistics$Interval.add(IntervalStatistics.java:168)
	at de.dennisguse.opentracks.viewmodels.IntervalStatistics$Interval.-$$Nest$madd(IntervalStatistics.java)
	at de.dennisguse.opentracks.viewmodels.IntervalStatistics.addTrackPoints(IntervalStatistics.java:51)
	at de.dennisguse.opentracks.viewmodels.IntervalStatisticsModel.lambda$loadIntervalStatistics$0$IntervalStatisticsModel(IntervalStatisticsModel.java:98)
	at de.dennisguse.opentracks.viewmodels.IntervalStatisticsModel$$ExternalSyntheticLambda0.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
```

**Comment by rgmf** [comment]
Seems that there is elevation gain but not loss. The code seems buggy in that case 🤔 

@dennisguse if you don't mind and you are busy with other things I'll look into this.

**Comment by dennisguse** [comment]
@rgmf That would be great!

**Comment by rgmf** [comment]
@FTno I think is fixed. You can check that https://github.com/OpenTracksApp/OpenTracks/pull/1002 fixes your issue or wait for a new release.

Thank you so much for your issue ;)
